### ISSUE TITLE
When and amount paid tests

### ISSUE THREAD

**Issue by Hjortsberg** [willeponken/d7032e-assignment-3#10]
Issue 501 to 506

**Comment by Hjortsberg** [comment]
I claim 501 to 503

**Comment by willeponken** [comment]
Hmmm

**Comment by willeponken** [comment]
I wanted to do 502!!!

**Comment by willeponken** [comment]
I claim 504 to 506 then... :crying_cat_face:

**Comment by Hjortsberg** [comment]
According to our spoken conversation we change the priorities here, 501, 502 and 505 is now mine.
@willeponken  is now assigned 503, 504 and 506.
